# -- The default [workload](https://jasonb5.github.io/charts/site/guide/common-library/#workload) type
workload: deployment

image:
  # -- Container image repository
  repository: gotify/server
  # -- Image tag
  # @default -- Chart.AppVersion
  tag:

# -- Gotify [configuration](https://gotify.net/docs/config#config-file)
env:
  # -- Set the timezone
  TZ: UTC
  # -- Default user name
  GOTIFY_DEFAULTUSER_NAME: "admin"
  # -- Default user password
  GOTIFY_DEFAULTUSER_PASS: "admin"
  # -- Enable user registration
  GOTIFY_REGISTRATION: "false"

# -- [Service](https://jasonb5.github.io/charts/site/guide/common-library/#service)
service:
  ports:
    default:
      # -- Default port
      port: 80

# -- [Ingress](https://jasonb5.github.io/charts/site/guide/common-library/#ingress)
ingress:
  # -- Enable/disable ingress
  enabled: false
  hosts:
    # -- Reference default service
  - name: default
    # -- Ingress hostname
    host:
  # -- [TLS](https://jasonb5.github.io/charts/site/guide/common-library/#tls)
  tls:
    # -- Enable/disable tls
    enabled: false

# -- [Persistence](https://jasonb5.github.io/charts/site/guide/common-library/#persistence)
persistence:
  config:
    # -- Enable/disable persistence
    enabled: false
    # -- Type of volume mount
    type: pvc
    # -- Size of volume
    size: 1Gi
    # -- Mount path
    mountPath: /app/data
