# -- The default [workload](https://jasonb5.github.io/charts/site/guide/common-library/#workload) type
workload: deployment

image:
  # -- Container image repository
  repository: gotify/server
  # -- Image tag
  # @default -- Chart.AppVersion
  tag:

env:
  # -- Set the timezone
  TZ: UTC
  # -- Default server port
  GOTIFY_SERVER_PORT: "{{ .Values.service.ports.default.port }}"
  # -- Default username
  GOTIFY_DEFAULTUSER_NAME: admin
  # -- Default password
  GOTIFY_DEFAULTUSER_PASS: admin

# -- [Service](https://jasonb5.github.io/charts/site/guide/common-library/#service)
service:
  ports:
    default:
      # -- Default port
      port: 80

# -- [Ingress](https://jasonb5.github.io/charts/site/guide/common-library/#ingress)
ingress:
  # -- Enable/disable ingress
  enabled: false
  hosts:
    # -- Reference default service
  - name: default
    # -- Ingress host
    host:
  # -- [TLS](https://jasonb5.github.io/charts/site/guide/common-library/#tls)
  tls:
    # -- Enable/disable tls
    enabled: false

# -- [Persistence](https://jasonb5.github.io/charts/site/guide/common-library/#persistence)
persistence:
  data:
    # -- Enable/disable data mount
    enabled: false
    # -- Data mount path
    mountPath: /app/data
    # -- Type of volume mount
    type:

