# -- The default [workload](https://jasonb5.github.io/charts/site/guide/common-library/#workload) type
workload: deployment

image:
  # -- Container image repository
  repository: ghcr.io/linuxserver/piper
  # -- Image tag
  # @default -- Chart.AppVersion
  tag:

env:
  # -- Set the timezone
  TZ: UTC
  # -- Voice for Piper to use
  PIPER_VOICE: en_US-hfc_female-medium

# -- [Service](https://jasonb5.github.io/charts/site/guide/common-library/#service)
service:
  ports:
    default:
      # -- Default port
      port: 10200

# -- [Ingress](https://jasonb5.github.io/charts/site/guide/common-library/#ingress)
ingress:
  # -- Enable/disable ingress
  enabled: false
  hosts:
    # -- Reference default service
  - name: default
    # -- Ingress hostname
    host:
  # -- [TLS](https://jasonb5.github.io/charts/site/guide/common-library/#tls)
  tls:
    # -- Enable/disable tls
    enabled: false

# -- [Persistence](https://jasonb5.github.io/charts/site/guide/common-library/#persistence)
persistence:
  config:
    # -- Enable/disable persistence
    enabled: false
    # -- Type of volume mount
    type: pvc
    # -- Size of volume
    size: 1Gi
