github_url = "https://github.com/jasonb5/charts/"

[version]
current = "0.1.14"

regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump ollama to {new_version}"
tag_template = "ollama_v{new_version}"

[[file]]
src = "Chart.yaml"
search = "version: {current_version}"
