_src_path: ../../charts/template
app_version: 1.24.0
description: FreshRSS is an RSS aggregator and reader. It allows you to read and follow
    several news websites at a glance without the need to browse from one website
    to another.
homepage: http://freshrss.github.io/FreshRSS/
image: freshrss/freshrss
keywords: rss
mariadb_enabled: false
name: freshrss
port: 80
postgresql_enabled: false
redis_enabled: false
root_directory: ../..
sources: https://github.com/FreshRSS/FreshRSS
version: 0.1.4
