apiVersion: v2
name: grocy
version: 0.1.0
description: |
  Grocy is a web-based self-hosted groceries & household management solution for your home.

  Open Source. Built with passion. 
type: application
keywords:
  - groceries
home: https://grocy.info/
sources:
  - https://github.com/jasonb5/charts/tree/main/charts/grocy
  - https://github.com/grocy/grocy
dependencies:
- name: common
  version: 0.1.x
  repository: https://jasonb5.github.io/charts
maintainers:
  - name: jasonb5
appVersion: 4.0.3
