# -- The default [workload](https://jasonb5.github.io/charts/site/guide/common-library/#workload) type
workload: deployment

image:
  # -- Container image repository
  repository: photoprism/photoprism
  # -- Image tag
  # @default -- Chart.AppVersion
  tag:

# -- Photoprism config [options](https://docs.photoprism.app/getting-started/config-options/)
env:
  # -- Set the timezone
  TZ: UTC
  # -- Set password for `admin` user
  PHOTOPRISM_ADMIN_PASSWORD:
  # -- Enable/disable experimental features
  PHOTOPRISM_EXPERIMENTAL: false

# -- [Service](https://jasonb5.github.io/charts/site/guide/common-library/#service)
service:
  ports:
    default:
      # -- Default port
      port: 2342

# -- [Ingress](https://jasonb5.github.io/charts/site/guide/common-library/#ingress)
ingress:
  # -- Enable/disable ingress
  enabled: false
  hosts:
    # -- Reference default service
  - name: default
    # -- Ingress hostname
    host:
  # -- [TLS](https://jasonb5.github.io/charts/site/guide/common-library/#tls)
  tls:
    # -- Enable/disable tls
    enabled: false

# -- [Persistence](https://jasonb5.github.io/charts/site/guide/common-library/#persistence)
persistence:
  storage:
    # -- Enable/disable storage mount (sidecar, cache, and database)
    enabled: false
    mountPath: /photoprism/storage
    # -- Type of volume mount
    type:

  originals:
    # -- Enable/disable originals mount
    enabled: false
    mountPath: /photoprism/originals
    # -- Type of volume mount
    type:

  import:
    # -- Enable/disable import mount
    enabled: false
    mountPath: /photoprism/import
    # -- Type of volume mount
    type:
