apiVersion: v2
name: jellyfin
version: 0.1.7
description: 'Jellyfin is the volunteer-built media solution that puts you in control
  of your media. Stream to any device from your own server, with no strings attached.
  Your media, your server, your way.

  '
type: application
keywords:
- media
home: https://jellyfin.org/
sources:
- https://github.com/jasonb5/charts/tree/main/charts/jellyfin
- https://github.com/jellyfin/jellyfin
- https://github.com/linuxserver/docker-jellyfin
dependencies:
- name: common
  version: 0.1.x
  repository: https://jasonb5.github.io/charts
maintainers:
- name: jasonb5
appVersion: 10.9.6
