site_name: Homelab
site_url: https://jasonb5.github.io/charts
repo_url: https://github.com/jasonb5/charts

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: teal
  features:
    - navigation.tabs
    - content.code.copy

watch:
  - README.md

markdown_extensions: 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences

plugins:
  - search
  - awesome-pages
  - htmlproofer

dev_addr: 0.0.0.0:8000
