apiVersion: v2
name: mealie
version: 0.1.0
description: |
   A self-hosted recipe manager and meal planner with a RestAPI backend and a reactive frontend application built in Vue for a pleasant user experience for the whole family. 
type: application
keywords:
  - recipes
  - management
home: https://mealie.io/
sources:
  - https://github.com/jasonb5/charts/tree/main/charts/mealie
  - https://github.com/mealie-recipes/mealie
dependencies:
- name: common
  version: 0.1.x
  repository: https://jasonb5.github.io/charts
maintainers:
  - name: jasonb5
appVersion: nightly
