# -- The default [workload](https://jasonb5.github.io/charts/site/guide/common-library/#workload) type
workload: deployment

image:
  # -- Container image repository
  repository: ghcr.io/mealie-recipes/mealie
  # -- Image tag
  # @default -- Chart.AppVersion
  tag:

# -- Backend [configuration](https://nightly.mealie.io/documentation/getting-started/installation/backend-config/)
env:
  # -- Set the timezone
  TZ: UTC
  # -- Enable user signups
  ALLOW_SIGNUP: false
  # -- Application URL
  BASE_URL: 

# -- [Service](https://jasonb5.github.io/charts/site/guide/common-library/#service)
service:
  ports:
    default:
      # -- Default port
      port: 9000

# -- [Ingress](https://jasonb5.github.io/charts/site/guide/common-library/#ingress)
ingress:
  # -- Enable/disable ingress
  enabled: true
  hosts:
    # -- Reference default service
  - name: default
    # -- Ingress hostname
    host: test.angrydonkey.io
  # -- [TLS](https://jasonb5.github.io/charts/site/guide/common-library/#tls)
  tls:
    # -- Enable/disable tls
    enabled: false

# -- [Persistence](https://jasonb5.github.io/charts/site/guide/common-library/#persistence)
persistence:
  config:
    # -- Enable/disable persistence
    enabled: false
    # -- Type of volume mount
    type: pvc
    # -- Size of volume
    size: 1Gi
    # -- Volume mount path
    mountPath: /app/data
