# -- The default [workload](https://jasonb5.github.io/charts/site/guide/common-library/#workload) type
workload: deployment

image:
  # -- Container image repository
  repository: ghcr.io/zwave-js/zwave-js-ui
  # -- Image tag
  # @default -- Chart.AppVersion
  tag:

# -- Environment variables
# Customize environment [variables](https://zwave-js.github.io/zwave-js-ui/#/guide/env-vars)
env:
  # -- Set the timezone
  TZ: UTC

# -- [Service](https://jasonb5.github.io/charts/site/guide/common-library/#service)
service:
  ports:
    default:
      # -- Default port
      port: 8091

    websocket:
      # -- Web socket port
      port: 3000

# -- [Ingress](https://jasonb5.github.io/charts/site/guide/common-library/#ingress)
ingress:
  # -- Enable/disable ingress
  enabled: false
  hosts:
    # -- Reference default service
  - name: default
    # -- Ingress hostname
    host:
  # -- [TLS](https://jasonb5.github.io/charts/site/guide/common-library/#tls)
  tls:
    # -- Enable/disable tls
    enabled: false

# -- [Persistence](https://jasonb5.github.io/charts/site/guide/common-library/#persistence)
persistence:
  config:
    # -- Enable/disable config mount
    enabled: false
    # -- Config mount path
    mountPath: /usr/src/app/store
    # -- Type of volume mount
    type:

  # -- Z-Wave device mount
  zwave:
    # -- Enable/disable zwave device mount
    enabled: false
    # -- Mount must be a hostpath
    type: hostpath
    # -- Host path to Z-Wave device e.g. /dev/serial/by-id/...
    path:
    # -- Hostpath mount type must be CharDevice
    mountType: CharDevice
    # -- Mount zwave device path
    mountPath: /dev/zwave
