apiVersion: v2
name: homarr
version: 0.1.2
description: |
  Simplify the management of your server with Homarr - a sleek, modern dashboard that puts all of your apps and services at your fingertips. With Homarr, you can access and control everything in one convenient location. Homarr seamlessly integrates with the apps you've added, providing you with valuable information and giving you complete control. Installation is a breeze, and Homarr supports a wide range of deployment methods.
type: application
keywords:
- dashboard
home: https://homarr.dev/
sources:
- https://github.com/jasonb5/charts/tree/main/charts/homarr
- https://github.com/ajnart/homarr
dependencies:
- name: common
  version: 0.1.x
  repository: https://jasonb5.github.io/charts
maintainers:
- name: jasonb5
appVersion: 0.14.4
