_src_path: ../../charts/template
app_version: 3.1.0
description: Dashy is an open source, highly customizable, easy to use, privacy-respecting
    dashboard app.
homepage: https://dashy.to/
image: lissy93/dashy
keywords: dashboard
mariadb_enabled: false
name: dashy
port: 8080
postgresql_enabled: false
redis_enabled: false
root_directory: ../..
sources: https://github.com/Lissy93/dashy
version: 0.1.9
