apiVersion: v2
name: node-red
version: 0.1.1
description: |
  Node-RED is a programming tool for wiring together hardware devices, APIs and online services in new and interesting ways.It provides a browser-based editor that makes it easy to wire together flows using the wide range of nodes in the palette that can be deployed to its runtime in a single-click.
type: application
keywords:
- automation
- event-driven
home: https://nodered.org/
sources:
- https://github.com/jasonb5/charts/tree/main/charts/node-red
- https://github.com/node-red/node-red
dependencies:
- name: common
  version: 0.1.x
  repository: https://jasonb5.github.io/charts
maintainers:
- name: jasonb5
appVersion: 3.1.3-debian
