_src_path: template/
description: Empty chart.
homepage: https://github.com/jasonb5/charts
image: ''
keywords: ''
mariadb_enabled: false
name: commonlib
port: 80
postgresql_enabled: false
redis_enabled: false
sources: ''
version: 0.1.0
