apiVersion: v2
name: linkwarden
version: 0.1.3
description: 'Linkwarden is a self-hosted, open-source collaborative bookmark manager
  to collect, organize and archive webpages. The objective is to organize useful webpages
  and articles you find across the web in one place, and since useful webpages can
  go away (see the inevitability of Link Rot), Linkwarden also saves a copy of each
  webpage as a Screenshot and PDF, ensuring accessibility even if the original content
  is no longer available. Additionally, Linkwarden is designed with collaboration
  in mind, sharing links with the public and/or allowing multiple users to work together
  seamlessly.

  '
type: application
keywords:
- bookmark
- archive
home: https://linkwarden.app/
sources:
- https://github.com/jasonb5/charts/tree/main/charts/linkwarden
- https://github.com/linkwarden/linkwarden
dependencies:
- name: common
  version: 0.1.x
  repository: https://jasonb5.github.io/charts
- name: postgresql
  version: 12.10.x
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: postgresql.enabled
maintainers:
- name: jasonb5
appVersion: v2.6.0
