# -- The default [workload](https://jasonb5.github.io/charts/site/guide/common-library/#workload) type
workload: deployment

image:
  # -- Container image repository
  repository: ghcr.io/linkwarden/linkwarden
  # -- Image tag
  # @default -- Chart.AppVersion
  tag:

env:
  # -- Set the timezone
  TZ: UTC
  # -- Secret key used to hash tokens, sign/encrypt cookies and generate cryptogrphic keys
  NEXTAUTH_SECRET:
  # -- Url for postgresql database
  DATABASE_URL: '{{ include "common.postgresql.url" . }}'

# -- [Service](https://jasonb5.github.io/charts/site/guide/common-library/#service)
service:
  ports:
    default:
      # -- Default port
      port: 3000

# -- [Ingress](https://jasonb5.github.io/charts/site/guide/common-library/#ingress)
ingress:
  # -- Enable/disable ingress
  enabled: false
  hosts:
    # -- Reference default service
  - name: default
    # -- Ingress hostname
    host:
  # -- [TLS](https://jasonb5.github.io/charts/site/guide/common-library/#tls)
  tls:
    # -- Enable/disable tls
    enabled: false

# -- [Persistence](https://jasonb5.github.io/charts/site/guide/common-library/#persistence)
persistence:
  config:
    # -- Enable/disable persistence
    enabled: false
    # -- Type of volume mount
    type: pvc
    # -- Size of volume
    size: 1Gi
    mountPath: /data/data

# -- PostgreSQL server, see Bitnami chart for [values](https://github.com/bitnami/charts/tree/main/bitnami/postgresql#parameters)
postgresql:
  enabled: true
  architecture: standalone
  auth:
    # -- Root database password
    postgresPassword:
    database: linkwarden
    username: linkwarden
    # -- Database password
    password:
  primary:
    persistence:
      enabled: false
  readReplicas:
    persistence:
      enabled: false
  metrics:
    enabled: false
