apiVersion: v2
name: common-test
description: A Helm chart for Kubernetes
type: application
version: 0.1.2
appVersion: "0.1.0"
dependencies:
- name: common
  version: "0.1.x"
  repository: "file://../common"
