_src_path: ../template/
description: An open source alternative front-end to YouTube.
homepage: https://invidious.io/
image: quay.io/invidious/invidious
keywords: video,audio,youtube
mariadb_enabled: false
name: invidious
port: 3000
postgresql_enabled: true
postgresql_version: 0.1.0
redis_enabled: false
relative_makefile: ../
sources: https://github.com/iv-org
version: 2024.03.31-08390ac
