github_url = "https://github.com/jasonb5/charts/"

[version]
current = "b0386174-ls65 "

regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump lazylibrarian to {new_version}"
tag_template = "lazylibrarian_v{new_version}"

[[file]]
src = "Chart.yaml"
search = "version: {current_version}"
