_src_path: ../template/
description: This is a powerful locally hosted web based PDF manipulation tool using
    docker that allows you to perform various operations on PDF files, such as splitting
    merging, converting, reorganizing, adding images, rotating, compressing, and more.
    This locally hosted web application started as a 100% ChatGPT-made application
    and has evolved to include a wide range of features to handle all your PDF needs.
homepage: https://github.com/Stirling-Tools/Stirling-PDF
image: frooodle/s-pdf
keywords: pdf
mariadb_enabled: false
name: stirling-pdf
port: 8080
postgresql_enabled: false
redis_enabled: false
relative_makefile: ../
sources: https://github.com/Stirling-Tools/Stirling-PDF
version: 0.22.8
