name: auto-update

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  list_charts:
    runs-on: ubuntu-latest
    name: List charts
    outputs:
      charts: ${{ steps.list_charts.outputs.charts }}
    steps:
      - uses: actions/checkout@v4
      - id: list_charts
        run: |
          echo "charts=$(ls charts/ | grep -vE 'common(-test)?|template|Makefile' | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  check_update:
    runs-on: ubuntu-latest
    name: Check for chart updates
    needs: list_charts
    strategy:
      matrix:
        chart_dir: ${{ fromJson(needs.list_charts.outputs.charts) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install semver requests pyyaml tbump
      - run: |
          python scripts/update-chart.py charts/${{ matrix.chart_dir }} --token ${{ secrets.GITHUB_TOKEN }} --in-place
      - name: Verify changed files
        uses: tj-actions/verify-changed-files@v16
        id: verify-changed-files
      - name: Create PR
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git remote -v
          cat .git/config
          git fetch origin
          git checkout -b updates_${{ matrix.chart_dir }} main
          pushd charts/${{ matrix.charts_dir }}
          make bump-patch
          git add .
          git commit -m "Updates ${{ matrix.chart_dir }} chart"
          gh pr create --fill
