name: auto-update

on:
  schedule:
    - cron: '0 2 * * *'

  workflow_dispatch:

jobs:
  list_charts:
    runs-on: ubuntu-latest
    name: List charts
    outputs:
      charts: ${{ steps.list_charts.outputs.charts }}
    steps:
      - uses: actions/checkout@v4
      - id: list_charts
        run: |
          echo "charts=$(ls charts/ | grep -vE 'common(-test)?|template|Makefile' | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  check_update:
    runs-on: ubuntu-latest
    name: Check for chart updates
    needs: list_charts
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        chart: ${{ fromJson(needs.list_charts.outputs.charts) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          path: main
      - name: Fix branch to target main
        working-directory: ./main
        run: |
          git fetch
          git reset --hard HEAD
          git checkout main
      - name: Check for container tag update
        id: check_chart
        run: |
          pip install semver requests tbump pyyaml

          new_version="$(python scripts/chart-updater.py --log --log-level DEBUG --log-file ./output.log update --in-place --token ${{ secrets.GITHUB_TOKEN }} main/charts/${{ matrix.chart }})"

          cat output.log

          pushd main/

          if [-n "$(git diff --name-only charts/${{ matrix.chart }})" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "new_version=${new_version}" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "new_version=" >> $GITHUB_OUTPUT
          fi
      - name: Make new branch and create PR
        working-directory: ./main
        if: steps.check_chart.outputs.changed == 'true'
        run: |
          pip install -r docs/requirements.txt

          git config user.email ${{ github.actor }}@users.noreply.github.com
          git config user.name ${{ github.actor }}

          git checkout -b updates_${{ matrix.chart }}

          pushd charts/${{ matrix.chart }}

          make docs
          git add .
          git commit -m "Updates ${{ matrix.chart }} to ${{ steps.check_chart.outputs.new_version }}"
          git push -u origin updates_${{ matrix.chart }}

          make bump-patch ARGS="--non-interactive"

          gh pr create --fill
