name: auto-merge

on:
  pull_request:
    types:
      - labeled
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    name: Auto merge PR based on label
    if: ${{ github.event.label.name == 'merge' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-helm-docs
      - name: Bump patch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install tbump semver

          make bump-patch ARGS="--non-interactive"
      - name: Update docs
        run: |
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git config user.name ${{ github.actor }}

          make docs

          git add .
          git commit -m "Updates docs"
          git push -u origin ${{ github.head_ref }}
      - name: Merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.number }} --delete-branch
