name: auto-update

on:
  schedule:
    - cron: '0 2 * * *'

  workflow_dispatch:

jobs:
  list-charts:
    runs-on: ubuntu-latest
    name: List charts
    outputs:
      charts: ${{ steps.list-charts.outputs.charts }}
    steps:
      - uses: actions/checkout@v4
      - id: list-charts
        run: |
          echo "charts=$(ls charts/ | grep -vE 'common(-test)?|template|Makefile|test_chart.py' | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  check-update:
    runs-on: ubuntu-latest
    name: Check for chart updates
    needs: list-charts
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        chart: ${{ fromJson(needs.list-charts.outputs.charts) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          path: main
      - name: Fix branch to target main
        working-directory: ./main
        run: |
          git fetch
          git reset --hard HEAD
          git checkout main
      - name: Check for container tag update
        id: check-chart
        run: |
          pip install -r requirements.txt

          pushd main/charts/${{ matrix.chart }}

          make update \
            ARGS="--log --log-level DEBUG -i --token ${{secrets.GITHUB_TOKEN}}"

          new_version=`make version`

          popd

          pushd main/

          if [ -n "$(git diff --name-only charts/${{ matrix.chart }})" ]; then
            echo "new_version=${new_version}" >> $GITHUB_OUTPUT

            branch_name="updates_${{ matrix.chart }}_${new_version}"

            if [ -n "$(git branch -a | grep ${branch_name})" ]
            then
              echo "changed=false" >> $GITHUB_OUTPUT
            else
              git checkout -b ${branch_name}

              echo "changed=true" >> $GITHUB_OUTPUT
              echo "branch_name=${branch_name}" >> $GITHUB_OUTPUT
            fi
          else
            echo "new_version=" >> $GITHUB_OUTPUT
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Make new branch and create PR
        working-directory: ./main
        if: steps.check-chart.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git config user.name ${{ github.actor }}

          pushd charts/${{ matrix.chart }}

          make dep

          git add .
          git commit -m "Updates ${{ matrix.chart }} to ${{ steps.check-chart.outputs.new_version }}"
          git push -u origin ${{ steps.check-chart.outputs.branch_name }}

          gh pr create --fill --label needs-testing
