name: comment-labels

on:
  issue_comment:
    types:
      - created

jobs:
  needs-testing:
    runs-on: ubuntu-latest
    name: Process /test comment
    if: contains(github.event.comment.body, '/test')
    steps:
      - uses: actions/checkout@v4
      - name: Adds needs-testing label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.number && github.event.number || github.event.issue.pull_request.url }}
        run: |
          PR_NUMBER=${PR_URL##*/}
          gh pr edit $PR_NUMBER --add-label needs-testing
  merge:
    runs-on: ubuntu-latest
    name: Process /merge comment
    if: contains(github.event.comment.body, '/merge')
    steps:
      - uses: actions/checkout@v4
      - name: Adds merge label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.number && github.event.number || github.event.issue.pull_request.url }}
        run: |
          PR_NUMBER=${PR_URL##*/}
          gh pr edit $PR_NUMBER --add-label merge
