name: Publish containers

on:
  push:
    branches:
      - main
    paths:
      - 'dockerfiles/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    name: Detect changed dockerfiles
    permissions:
      contents: read
    outputs:
      charts: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Detect changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          dir_names: true
          path: dockerfiles/
          json: true
          escape_json: false
  build-push:
    runs-on: ubuntu-latest
    name: Build and push container
    permissions:
      contents: read
      packages: write
    needs: detect-changes
    strategy:
      matrix:
        chart_dir: ${{ fromJSON(needs.detect-changes.outputs.charts) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - id: get-current-version
        run: |
          pip install tbump

          pushd dockerfiles/${{ matrix.chart_dir }}

          echo "current_version=$(tbump current-version)" >> $GITHUB_OUTPUT
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: dockerfiles/${{ matrix.chart_dir }}
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/jasonb5/rclone:${{ steps.get-current-version.outputs.current_version }}
