name: testing

on:
  pull_request:
    paths:
      - 'charts/**'

  issue_comment:
    types:
      - created

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Get changed Helm charts
    outputs:
      all_modified_files: ${{ steps.changed-files-yaml.outputs.all_modified_files }}
    if: |
      github.event_name == 'pull_request' ||
      contains(github.event.comment.body, '/test')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout PR
        id: issue_ref
        if: ${{ github.event_name == 'issue_comment' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
        run: |
          echo "base_ref=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          gh co ${PR_NUMBER}
          echo "head_ref=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - run: |
          echo ${{ github.base_ref }}
          echo ${{ github.head_ref }}
      - name: Get all Helm charts that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v40.1.1
        with:
          dir_names: true
          dir_names_exclude_current_dir: true
          dir_names_max_depth: 1
          escape_json: false
          json: true
          path: 'charts/'
          files_ignore: 'template'
          fetch_depth: 0
          base_sha: ${{ github.event.pull_request && github.base_ref || steps.issue_ref.outputs.base_ref }}
          sha: ${{ github.event.pull_request && github.head_ref || steps.issue_ref.outputs.head_ref }}
  test_chart:
    runs-on: ubuntu-latest
    name: Test Helm chart
    needs: changed_files
    strategy:
      matrix:
        chart: ${{ fromJSON(needs.changed_files.outputs.all_modified_files) }}
    defaults:
      run:
        working-directory: ${{ format('charts/{0}', matrix.chart) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Lint Helm chart
        run: make lint
      - name: Unittest Helm chart
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git
          make test
      - name: Install k3d/setup k3s cluster
        uses: nolar/setup-k3d-k3s@v1
      - name: Install helm chart
        if: ${{ ! contains(matrix.chart, 'common') }}
        run: |
          helm install --wait test .
          name=$(kubectl get pods -oname)
          port=$(cat values.yaml | yq '.service.ports.default.port')
          kubectl port-forward $name 8000:${port} &
          sleep 2
          curl http://127.0.0.1:8000 -vvv
          killall kubectl
