name: testing

on:
  pull_request:
    paths:
      - 'charts/**'

  issue_comment:
    types:
      - created

jobs:
  changed-files:
    runs-on: ubuntu-latest
    name: Get changed Helm charts
    outputs:
      all_modified_files: ${{ steps.changed-files-yaml.outputs.all_modified_files }}
    if: |
      github.event_name == 'pull_request' ||
      contains(github.event.comment.body, '/test')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout PR
        id: issue-ref
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]];
          then
            git checkout ${{ github.base_ref }}
            echo "base_ref=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
            git checkout ${{ github.head_ref }}
            echo "head_ref=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          else
            echo "base_ref=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
            gh co ${{ github.event.issue.number }}
            echo "head_ref=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          fi
      - name: Get all Helm charts that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v40.1.1
        with:
          dir_names: true
          dir_names_exclude_current_dir: true
          dir_names_max_depth: 1
          escape_json: false
          json: true
          path: 'charts/'
          files_ignore: |
            template/**
            common-test/**
          fetch_depth: 0
          base_sha: ${{ steps.issue-ref.outputs.base_ref }}
          sha: ${{ steps.issue-ref.outputs.head_ref }}
  test-chart:
    runs-on: ubuntu-latest
    name: Test Helm chart
    needs: changed-files
    strategy:
      matrix:
        chart: ${{ fromJSON(needs.changed-files.outputs.all_modified_files) }}
    defaults:
      run:
        working-directory: ${{ format('charts/{0}', matrix.chart) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Install k3s
        uses: debianmaster/actions-k3s@v1.0.5
        with:
          version: 'latest'
      - name: Install tools
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git

          pip install -r ../../requirements.txt
      - name: Lint Helm chart
        run: make lint
      - name: Install Helm chart
        if: ${{ ! contains(matrix.chart, 'common') }}
        run: |
          make install
          make open &
      - name: Unittest Helm chart
        run: make test
      - name: Remove needs-testing label on success
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.number && github.event.number || github.event.issue.pull_request.url }}
        run: |
          PR_NUM=${PR_URL##*/}
          gh pr edit $PR_NUM --remove-label needs-testing
